# ul.rb
# -------------
#   troff
# -------------
#
#   §10.3
#
# Request  Initial  If no     Notes   Explanation
#  form     value   argument
#
# .ul N    off      N=1       E       Underline in nroff (italicize in troff) the next N
#                                     input text lines. Actually, switch to the underline
#                                     font, saving the current font for later restoration;
#                                     other font changes within the span of a .ul will
#                                     take effect, but the restoration will undo the last
#                                     change. Output generated by .tl is affected by the
#                                     font change, but does not decrement N. (See section
#                                     14, "Three Part Titles.") If N>1, there is a risk
#                                     that the trap-invoked macro may provide text lines
#                                     within the span; environment switching can prevent
#                                     this.
#
#  TODO - figure out if the .tl / trap-invoked macro / environment switching part
#         matters to us in any way.
#

module Troff
  def req_ul(n = '1')
    req_ft('I')
    req_it(n, :finalize_ul)
  end

  def finalize_ul
    req_ft
  end
end
